### ISSUE TITLE
Где лабы алло

### ISSUE THREAD

**Issue by yeilya** [Ivanko5417/ES#1]
Почему нет лаб 5-го варианта я не понял?

**Comment by Ivanko5417** [comment]
Здравствуй @yeilya , вы можете создать Pull Request.

**Comment by mikitasolo** [comment]
Any updates on the issue?

**Comment by Ivanko5417** [comment]
Looks like @yeilya decided to do nothing. Lazy Russians....

**Comment by yeilya** [comment]
themselves lazy, @obmeraz will contribute.
